package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1



/**
 * AppartenirgroupeId generated by hbm2java
 */
public class AppartenirgroupeId  implements java.io.Serializable {


     private int numetudiant;
     private int codeg;

    public AppartenirgroupeId() {
    }

    public AppartenirgroupeId(int numetudiant, int codeg) {
       this.numetudiant = numetudiant;
       this.codeg = codeg;
    }
   
    public int getNumetudiant() {
        return this.numetudiant;
    }
    
    public void setNumetudiant(int numetudiant) {
        this.numetudiant = numetudiant;
    }
    public int getCodeg() {
        return this.codeg;
    }
    
    public void setCodeg(int codeg) {
        this.codeg = codeg;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + this.numetudiant;
        hash = 67 * hash + this.codeg;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AppartenirgroupeId other = (AppartenirgroupeId) obj;
        if (this.numetudiant != other.numetudiant) {
            return false;
        }
        if (this.codeg != other.codeg) {
            return false;
        }
        return true;
    }



   



}


