package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
public class Cours  implements java.io.Serializable {


     private Integer codec;
     private String nomc;
     private Formation formation;
     private String typec;
     private String uec;
     private Set enseignants = new HashSet(0);
     private Set creneaus = new HashSet(0);
     private Set groupes = new HashSet(0);

    public Cours() {
    }

	
    public Cours(Formation formation) {
        this.formation = formation;
    }
    public Cours(String nomc, Formation formation, String typec, String uec, Set enseignants, Set creneaus, Set groupes) {
       this.nomc=nomc;
        this.formation = formation;
       this.typec = typec;
       this.uec = uec;
       this.enseignants = enseignants;
       this.creneaus = creneaus;
       this.groupes = groupes;
    }
   
    public Integer getCodec() {
        return this.codec;
    }
    
    public void setCodec(Integer codec) {
        this.codec = codec;
    }

    public String getNomc() {
        return nomc;
    }

    public void setNomc(String nomc) {
        this.nomc = nomc;
    }


    public Formation getFormation() {
        return this.formation;
    }
    
    public void setFormation(Formation formation) {
        this.formation = formation;
    }
    public String getTypec() {
        return this.typec;
    }
    
    public void setTypec(String typec) {
        this.typec = typec;
    }
    public String getUec() {
        return this.uec;
    }
    
    public void setUec(String uec) {
        this.uec = uec;
    }
    public Set getEnseignants() {
        return this.enseignants;
    }
    
    public void setEnseignants(Set enseignants) {
        this.enseignants = enseignants;
    }
    public Set getCreneaus() {
        return this.creneaus;
    }
    
    public void setCreneaus(Set creneaus) {
        this.creneaus = creneaus;
    }
    public Set getGroupes() {
        return this.groupes;
    }
    
    public void setGroupes(Set groupes) {
        this.groupes = groupes;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.codec);
        hash = 67 * hash + Objects.hashCode(this.nomc);
        hash = 67 * hash + Objects.hashCode(this.formation);
        hash = 67 * hash + Objects.hashCode(this.typec);
        hash = 67 * hash + Objects.hashCode(this.uec);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cours other = (Cours) obj;
        if (!Objects.equals(this.nomc, other.nomc)) {
            return false;
        }
        if (!Objects.equals(this.typec, other.typec)) {
            return false;
        }
        if (!Objects.equals(this.uec, other.uec)) {
            return false;
        }
        if (!Objects.equals(this.codec, other.codec)) {
            return false;
        }
        if (!Objects.equals(this.formation, other.formation)) {
            return false;
        }
        return true;
    }




}


