package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Creneau generated by hbm2java
 */
public class Creneau implements java.io.Serializable {

    private Integer codecre;
    private Cours cours;
    private Enseignant enseignant;
    private Groupe groupe;
    private String nomcre;

    public String getNomcre() {
        return nomcre;
    }

    public void setNomcre(String nomcre) {
        this.nomcre = nomcre;
    }
    private Date datecre;
    private Long dureecre;
    private Date heuredeb;
    private String typeactivitecre;
    private Set etreprersenters = new HashSet(0);

    public Creneau() {
    }

    public Creneau(Enseignant enseignant) {
        this.enseignant = enseignant;
    }

    public Creneau(String typeactivitecre) {
        this.typeactivitecre = typeactivitecre;
    }

    public Creneau(Cours cours, Date datecre, String typeactivitecre) {
        this.cours = cours;
        this.enseignant = enseignant;
        this.groupe = groupe;
        this.datecre = datecre;
        this.dureecre = dureecre;
        this.heuredeb = heuredeb;
        this.typeactivitecre = typeactivitecre;
        this.etreprersenters = etreprersenters;
    }

    public Creneau(Cours cours, Enseignant enseignant, Groupe groupe, Date datecre, Long dureecre, Date heuredeb, String typeactivitecre, Set etreprersenters) {
        this.cours = cours;
        this.enseignant = enseignant;
        this.groupe = groupe;
        this.datecre = datecre;
        this.dureecre = dureecre;
        this.heuredeb = heuredeb;
        this.typeactivitecre = typeactivitecre;
        this.etreprersenters = etreprersenters;
    }

    public Creneau(Cours cours, String nomcre, Enseignant enseignant, Groupe groupe, Date datecre, Long dureecre, Date heuredeb, String typeactivitecre) {
        this.cours = cours;
        this.nomcre = nomcre;
        this.enseignant = enseignant;
        this.groupe = groupe;
        this.datecre = datecre;
        this.dureecre = dureecre;
        this.heuredeb = heuredeb;
        this.typeactivitecre = typeactivitecre;
    }

    public Integer getCodecre() {
        return this.codecre;
    }

    public void setCodecre(Integer codecre) {
        this.codecre = codecre;
    }

    public Cours getCours() {
        return this.cours;
    }

    public void setCours(Cours cours) {
        this.cours = cours;
    }

    public Enseignant getEnseignant() {
        return this.enseignant;
    }

    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }

    public Groupe getGroupe() {
        return this.groupe;
    }

    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }

    public Date getDatecre() {
        return this.datecre;
    }

    public void setDatecre(Date datecre) {
        this.datecre = datecre;
    }

    public Long getDureecre() {
        return this.dureecre;
    }

    public void setDureecre(Long dureecre) {
        this.dureecre = dureecre;
    }

    public Date getHeuredeb() {
        return this.heuredeb;
    }

    public void setHeuredeb(Date heuredeb) {
        this.heuredeb = heuredeb;
    }

    public String getTypeactivitecre() {
        return this.typeactivitecre;
    }

    public void setTypeactivitecre(String typeactivitecre) {
        this.typeactivitecre = typeactivitecre;
    }

    public Set getEtreprersenters() {
        return this.etreprersenters;
    }

    public void setEtreprersenters(Set etreprersenters) {
        this.etreprersenters = etreprersenters;
    }

    @Override
    public String toString() {
        return "Creneau{" + "codecre=" + codecre + ", cours=" + cours + ", enseignant=" + enseignant + ", groupe=" + groupe + ", datecre=" + datecre + ", dureecre=" + dureecre + ", heuredeb=" + heuredeb + ", typeactivitecre=" + typeactivitecre + ", etreprersenters=" + etreprersenters + '}';
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 43 * hash + Objects.hashCode(this.codecre);
        hash = 43 * hash + Objects.hashCode(this.cours);
        hash = 43 * hash + Objects.hashCode(this.enseignant);
        hash = 43 * hash + Objects.hashCode(this.groupe);
        hash = 43 * hash + Objects.hashCode(this.datecre);
        hash = 43 * hash + Objects.hashCode(this.dureecre);
        hash = 43 * hash + Objects.hashCode(this.heuredeb);
        hash = 43 * hash + Objects.hashCode(this.typeactivitecre);
        hash = 43 * hash + Objects.hashCode(this.etreprersenters);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Creneau other = (Creneau) obj;
        if (!Objects.equals(this.typeactivitecre, other.typeactivitecre)) {
            return false;
        }
        if (!Objects.equals(this.codecre, other.codecre)) {
            return false;
        }
        if (!Objects.equals(this.cours, other.cours)) {
            return false;
        }
        if (!Objects.equals(this.enseignant, other.enseignant)) {
            return false;
        }
        if (!Objects.equals(this.groupe, other.groupe)) {
            return false;
        }
        if (!Objects.equals(this.datecre, other.datecre)) {
            return false;
        }
        if (!Objects.equals(this.dureecre, other.dureecre)) {
            return false;
        }
        if (!Objects.equals(this.heuredeb, other.heuredeb)) {
            return false;
        }
        if (!Objects.equals(this.etreprersenters, other.etreprersenters)) {
            return false;
        }
        return true;
    }

}
