package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1

/**
 * EtreprersenterId generated by hbm2java
 */
public class EtreprersenterId implements java.io.Serializable {

    private int codecre;
    private int numetudiant;

    public EtreprersenterId() {
    }

    public EtreprersenterId(int codecre, int numetudiant) {
        this.codecre = codecre;
        this.numetudiant = numetudiant;
    }

    public int getCodecre() {
        return this.codecre;
    }

    public void setCodecre(int codecre) {
        this.codecre = codecre;
    }

    public int getNumetudiant() {
        return this.numetudiant;
    }

    public void setNumetudiant(int numetudiant) {
        this.numetudiant = numetudiant;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof EtreprersenterId)) {
            return false;
        }
        EtreprersenterId castOther = (EtreprersenterId) other;

        return (this.getCodecre() == castOther.getCodecre())
                && (this.getNumetudiant() == castOther.getNumetudiant());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCodecre();
        result = 37 * result + this.getNumetudiant();
        return result;
    }

    @Override
    public String toString() {
        return "EtreprersenterId{" + "codecre=" + codecre + ", numetudiant=" + numetudiant + '}';
    }

}
