package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant implements java.io.Serializable {

    private Integer numetudiant;
    private Formation formation;
    private String mailetu;
    private String mdpetu;
    private String nometu;
    private String prenometu;
    private String photoetu;
    private String adressesoc;
    private String mailsoc;
    private String raisonsoc;
    private String typeetu;
    private Set appartenirgroupes = new HashSet(0);
    private Set etreprersenters = new HashSet(0);
    private Set ficheindividuelles = new HashSet(0);

    public Etudiant() {
    }

    public Etudiant(Formation formation) {
        this.formation = formation;
    }

    public Etudiant(Formation formation, String mailetu, String mdpetu, String nometu, String prenometu, String photoetu, String adressesoc, String mailsoc, String raisonsoc, String typeetu, Set appartenirgroupes, Set etreprersenters, Set ficheindividuelles) {
        this.formation = formation;
        this.mailetu = mailetu;
        this.mdpetu = mdpetu;
        this.nometu = nometu;
        this.prenometu = prenometu;
        this.photoetu = photoetu;
        this.adressesoc = adressesoc;
        this.mailsoc = mailsoc;
        this.raisonsoc = raisonsoc;
        this.typeetu = typeetu;
        this.appartenirgroupes = appartenirgroupes;
        this.etreprersenters = etreprersenters;
        this.ficheindividuelles = ficheindividuelles;
    }

    public Integer getNumetudiant() {
        return this.numetudiant;
    }

    public void setNumetudiant(Integer numetudiant) {
        this.numetudiant = numetudiant;
    }

    public Formation getFormation() {
        return this.formation;
    }

    public void setFormation(Formation formation) {
        this.formation = formation;
    }

    public String getMailetu() {
        return this.mailetu;
    }

    public void setMailetu(String mailetu) {
        this.mailetu = mailetu;
    }

    public String getMdpetu() {
        return this.mdpetu;
    }

    public void setMdpetu(String mdpetu) {
        this.mdpetu = mdpetu;
    }

    public String getNometu() {
        return this.nometu;
    }

    public void setNometu(String nometu) {
        this.nometu = nometu;
    }

    public String getPrenometu() {
        return this.prenometu;
    }

    public void setPrenometu(String prenometu) {
        this.prenometu = prenometu;
    }

    public String getPhotoetu() {
        return this.photoetu;
    }

    public void setPhotoetu(String photoetu) {
        this.photoetu = photoetu;
    }

    public String getAdressesoc() {
        return this.adressesoc;
    }

    public void setAdressesoc(String adressesoc) {
        this.adressesoc = adressesoc;
    }

    public String getMailsoc() {
        return this.mailsoc;
    }

    public void setMailsoc(String mailsoc) {
        this.mailsoc = mailsoc;
    }

    public String getRaisonsoc() {
        return this.raisonsoc;
    }

    public void setRaisonsoc(String raisonsoc) {
        this.raisonsoc = raisonsoc;
    }

    public String getTypeetu() {
        return this.typeetu;
    }

    public void setTypeetu(String typeetu) {
        this.typeetu = typeetu;
    }

    public Set getAppartenirgroupes() {
        return this.appartenirgroupes;
    }

    public void setAppartenirgroupes(Set appartenirgroupes) {
        this.appartenirgroupes = appartenirgroupes;
    }

    public Set getEtreprersenters() {
        return this.etreprersenters;
    }

    public void setEtreprersenters(Set etreprersenters) {
        this.etreprersenters = etreprersenters;
    }

    public Set getFicheindividuelles() {
        return this.ficheindividuelles;
    }

    public void setFicheindividuelles(Set ficheindividuelles) {
        this.ficheindividuelles = ficheindividuelles;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.numetudiant);
        hash = 67 * hash + Objects.hashCode(this.mailetu);
        hash = 67 * hash + Objects.hashCode(this.mdpetu);
        hash = 67 * hash + Objects.hashCode(this.nometu);
        hash = 67 * hash + Objects.hashCode(this.prenometu);
        hash = 67 * hash + Objects.hashCode(this.photoetu);
        hash = 67 * hash + Objects.hashCode(this.adressesoc);
        hash = 67 * hash + Objects.hashCode(this.mailsoc);
        hash = 67 * hash + Objects.hashCode(this.raisonsoc);
        hash = 67 * hash + Objects.hashCode(this.typeetu);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Etudiant other = (Etudiant) obj;
        if (!Objects.equals(this.mailetu, other.mailetu)) {
            return false;
        }
        if (!Objects.equals(this.mdpetu, other.mdpetu)) {
            return false;
        }
        if (!Objects.equals(this.nometu, other.nometu)) {
            return false;
        }
        if (!Objects.equals(this.prenometu, other.prenometu)) {
            return false;
        }
        if (!Objects.equals(this.photoetu, other.photoetu)) {
            return false;
        }
        if (!Objects.equals(this.adressesoc, other.adressesoc)) {
            return false;
        }
        if (!Objects.equals(this.mailsoc, other.mailsoc)) {
            return false;
        }
        if (!Objects.equals(this.raisonsoc, other.raisonsoc)) {
            return false;
        }
        if (!Objects.equals(this.typeetu, other.typeetu)) {
            return false;
        }
        if (!Objects.equals(this.numetudiant, other.numetudiant)) {
            return false;
        }
        return true;
    }

}
