package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1

import java.util.Objects;


/**
 * Ficheindividuelle generated by hbm2java
 */
public class Ficheindividuelle implements java.io.Serializable {

    private int codefi;
    private Etudiant etudiant;
    private Boolean etatvalide;
    private String attestation;
    private String moisfiche;
    private String anneefiche;
    private String urlfic;

    public Ficheindividuelle() {
    }

    public Ficheindividuelle(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    //constructeur pour etudiant upload fichier 
    public Ficheindividuelle(Etudiant etudiant, String moisfiche, String anneefiche, String urlfic,Boolean etatvalide) {
        this.etudiant = etudiant;
        this.moisfiche = moisfiche;
        this.anneefiche = anneefiche;
        this.urlfic = urlfic;
    }
    public Ficheindividuelle(int codefi, Etudiant etudiant, Boolean etatvalide, String attestation, String moisfiche, String anneefiche, String urlfic) {
        this.codefi = codefi;
        this.etudiant = etudiant;
        this.etatvalide = etatvalide;
        this.attestation = attestation;
        this.moisfiche = moisfiche;
        this.anneefiche = anneefiche;
        this.urlfic = urlfic;
    }

    public String getMoisfiche() {
        return moisfiche;
    }

    public void setMoisfiche(String moisfiche) {
        this.moisfiche = moisfiche;
    }

    public String getAnneefiche() {
        return anneefiche;
    }

    public void setAnneefiche(String anneefiche) {
        this.anneefiche = anneefiche;
    }

    public String getUrlfic() {
        return urlfic;
    }

    public void setUrlfic(String urlfic) {
        this.urlfic = urlfic;
    }

    public Ficheindividuelle(Etudiant etudiant, Boolean etatvalide, String attestation) {
        this.etudiant = etudiant;
        this.etatvalide = etatvalide;
        this.attestation = attestation;
    }

    public int getCodefi() {
        return codefi;
    }

    public void setCodefi(int codefi) {
        this.codefi = codefi;
    }

    public Etudiant getEtudiant() {
        return this.etudiant;
    }

    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }

    public Boolean getEtatvalide() {
        return this.etatvalide;
    }

    public void setEtatvalide(Boolean etatvalide) {
        this.etatvalide = etatvalide;
    }

    public String getAttestation() {
        return this.attestation;
    }

    public void setAttestation(String attestation) {
        this.attestation = attestation;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 31 * hash + this.codefi;
        hash = 31 * hash + Objects.hashCode(this.etatvalide);
        hash = 31 * hash + Objects.hashCode(this.attestation);
        hash = 31 * hash + Objects.hashCode(this.moisfiche);
        hash = 31 * hash + Objects.hashCode(this.anneefiche);
        hash = 31 * hash + Objects.hashCode(this.urlfic);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Ficheindividuelle other = (Ficheindividuelle) obj;
        if (this.codefi != other.codefi) {
            return false;
        }
        if (!Objects.equals(this.attestation, other.attestation)) {
            return false;
        }
        if (!Objects.equals(this.moisfiche, other.moisfiche)) {
            return false;
        }
        if (!Objects.equals(this.anneefiche, other.anneefiche)) {
            return false;
        }
        if (!Objects.equals(this.urlfic, other.urlfic)) {
            return false;
        }
        if (!Objects.equals(this.etatvalide, other.etatvalide)) {
            return false;
        }
        return true;
    }

}
