package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Formation generated by hbm2java
 */
public class Formation  implements java.io.Serializable {


     private Integer codef;
     private String nomf;
     private String typef;
     private Set periodes = new HashSet(0);
     private Set etudiants = new HashSet(0);
     private Set courses = new HashSet(0);
     private Set enseignants = new HashSet(0);
     private Set gestionnairescolarites = new HashSet(0);

    public Formation() {
    }

    public Formation(String nomf, String typef, Set periodes, Set etudiants, Set courses, Set enseignants, Set gestionnairescolarites) {
       this.nomf = nomf;
       this.typef = typef;
       this.periodes = periodes;
       this.etudiants = etudiants;
       this.courses = courses;
       this.enseignants = enseignants;
       this.gestionnairescolarites = gestionnairescolarites;
    }
   
    public Integer getCodef() {
        return this.codef;
    }
    
    public void setCodef(Integer codef) {
        this.codef = codef;
    }
    public String getNomf() {
        return this.nomf;
    }
    
    public void setNomf(String nomf) {
        this.nomf = nomf;
    }
    public String getTypef() {
        return this.typef;
    }
    
    public void setTypef(String typef) {
        this.typef = typef;
    }
    public Set getPeriodes() {
        return this.periodes;
    }
    
    public void setPeriodes(Set periodes) {
        this.periodes = periodes;
    }
    public Set getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set etudiants) {
        this.etudiants = etudiants;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
    public Set getEnseignants() {
        return this.enseignants;
    }
    
    public void setEnseignants(Set enseignants) {
        this.enseignants = enseignants;
    }
    public Set getGestionnairescolarites() {
        return this.gestionnairescolarites;
    }
    
    public void setGestionnairescolarites(Set gestionnairescolarites) {
        this.gestionnairescolarites = gestionnairescolarites;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 13 * hash + Objects.hashCode(this.codef);
        hash = 13 * hash + Objects.hashCode(this.nomf);
        hash = 13 * hash + Objects.hashCode(this.typef);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Formation other = (Formation) obj;
        if (!Objects.equals(this.nomf, other.nomf)) {
            return false;
        }
        if (!Objects.equals(this.typef, other.typef)) {
            return false;
        }
        if (!Objects.equals(this.codef, other.codef)) {
            return false;
        }
        return true;
    }




}


