package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Gestionnairescolarite generated by hbm2java
 */
public class Gestionnairescolarite  implements java.io.Serializable {


     private Integer codegs;
     private String mailgs;
     private String mdpgs;
     private String nomgs;
     private String prenomgs;
     private String contactgs;
     private Set formations = new HashSet(0);

    public Gestionnairescolarite() {
    }

    public Gestionnairescolarite(String mailgs, String mdpgs, String nomgs, String prenomgs, String contactgs, Set formations) {
       this.mailgs = mailgs;
       this.mdpgs = mdpgs;
       this.nomgs = nomgs;
       this.prenomgs = prenomgs;
       this.contactgs = contactgs;
       this.formations = formations;
    }
   
    public Integer getCodegs() {
        return this.codegs;
    }
    
    public void setCodegs(Integer codegs) {
        this.codegs = codegs;
    }
    public String getMailgs() {
        return this.mailgs;
    }
    
    public void setMailgs(String mailgs) {
        this.mailgs = mailgs;
    }
    public String getMdpgs() {
        return this.mdpgs;
    }
    
    public void setMdpgs(String mdpgs) {
        this.mdpgs = mdpgs;
    }
    public String getNomgs() {
        return this.nomgs;
    }
    
    public void setNomgs(String nomgs) {
        this.nomgs = nomgs;
    }
    public String getPrenomgs() {
        return this.prenomgs;
    }
    
    public void setPrenomgs(String prenomgs) {
        this.prenomgs = prenomgs;
    }
    public String getContactgs() {
        return this.contactgs;
    }
    
    public void setContactgs(String contactgs) {
        this.contactgs = contactgs;
    }
    public Set getFormations() {
        return this.formations;
    }
    
    public void setFormations(Set formations) {
        this.formations = formations;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.codegs);
        hash = 67 * hash + Objects.hashCode(this.mailgs);
        hash = 67 * hash + Objects.hashCode(this.mdpgs);
        hash = 67 * hash + Objects.hashCode(this.nomgs);
        hash = 67 * hash + Objects.hashCode(this.prenomgs);
        hash = 67 * hash + Objects.hashCode(this.contactgs);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Gestionnairescolarite other = (Gestionnairescolarite) obj;
        if (!Objects.equals(this.mailgs, other.mailgs)) {
            return false;
        }
        if (!Objects.equals(this.mdpgs, other.mdpgs)) {
            return false;
        }
        if (!Objects.equals(this.nomgs, other.nomgs)) {
            return false;
        }
        if (!Objects.equals(this.prenomgs, other.prenomgs)) {
            return false;
        }
        if (!Objects.equals(this.contactgs, other.contactgs)) {
            return false;
        }
        if (!Objects.equals(this.codegs, other.codegs)) {
            return false;
        }
        return true;
    }




}


