package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Groupe generated by hbm2java
 */
public class Groupe implements java.io.Serializable {

    private Integer codeg;
    private String libelleg;
    private Set appartenirgroupes = new HashSet(0);
    private Set creneaus = new HashSet(0);
    private Set courses = new HashSet(0);

    public Groupe() {
    }

    public Groupe(String libelleg, Set appartenirgroupes, Set creneaus, Set courses) {
        this.libelleg = libelleg;
        this.appartenirgroupes = appartenirgroupes;
        this.creneaus = creneaus;
        this.courses = courses;
    }

    public Integer getCodeg() {
        return this.codeg;
    }

    public void setCodeg(Integer codeg) {
        this.codeg = codeg;
    }

    public String getLibelleg() {
        return this.libelleg;
    }

    public void setLibelleg(String libelleg) {
        this.libelleg = libelleg;
    }

    public Set getAppartenirgroupes() {
        return this.appartenirgroupes;
    }

    public void setAppartenirgroupes(Set appartenirgroupes) {
        this.appartenirgroupes = appartenirgroupes;
    }

    public Set getCreneaus() {
        return this.creneaus;
    }

    public void setCreneaus(Set creneaus) {
        this.creneaus = creneaus;
    }

    public Set getCourses() {
        return this.courses;
    }

    public void setCourses(Set courses) {
        this.courses = courses;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.codeg);
        hash = 37 * hash + Objects.hashCode(this.libelleg);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Groupe other = (Groupe) obj;
        if (!Objects.equals(this.libelleg, other.libelleg)) {
            return false;
        }
        if (!Objects.equals(this.codeg, other.codeg)) {
            return false;
        }
        return true;
    }

}
