package bd;
// Generated Mar 19, 2020 9:51:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;

/**
 * Periode generated by hbm2java
 */
public class Periode  implements java.io.Serializable {


     private Integer codep;
     private Formation formation;
     private Date datedebp;
     private Date datefinp;
     private String libellep;

    public Periode() {
    }

	
    public Periode(Formation formation) {
        this.formation = formation;
    }
    public Periode(Formation formation, Date datedebp, Date datefinp, String libellep) {
       this.formation = formation;
       this.datedebp = datedebp;
       this.datefinp = datefinp;
       this.libellep = libellep;
    }
   
    public Integer getCodep() {
        return this.codep;
    }
    
    public void setCodep(Integer codep) {
        this.codep = codep;
    }
    public Formation getFormation() {
        return this.formation;
    }
    
    public void setFormation(Formation formation) {
        this.formation = formation;
    }
    public Date getDatedebp() {
        return this.datedebp;
    }
    
    public void setDatedebp(Date datedebp) {
        this.datedebp = datedebp;
    }
    public Date getDatefinp() {
        return this.datefinp;
    }
    
    public void setDatefinp(Date datefinp) {
        this.datefinp = datefinp;
    }
    public String getLibellep() {
        return this.libellep;
    }
    
    public void setLibellep(String libellep) {
        this.libellep = libellep;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.codep);
        hash = 23 * hash + Objects.hashCode(this.datedebp);
        hash = 23 * hash + Objects.hashCode(this.datefinp);
        hash = 23 * hash + Objects.hashCode(this.libellep);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Periode other = (Periode) obj;
        if (!Objects.equals(this.libellep, other.libellep)) {
            return false;
        }
        if (!Objects.equals(this.codep, other.codep)) {
            return false;
        }
        if (!Objects.equals(this.datedebp, other.datedebp)) {
            return false;
        }
        if (!Objects.equals(this.datefinp, other.datefinp)) {
            return false;
        }
        return true;
    }




}


