package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
public class Cours  implements java.io.Serializable {


     private Integer codec;
     private Formation formation;
     private String nomc;
     private Set enseignants = new HashSet(0);
     private Set creneaus = new HashSet(0);
     private Set groupes = new HashSet(0);

    public Cours() {
    }

	
    public Cours(Formation formation, String nomc) {
        this.formation = formation;
        this.nomc = nomc;
    }
    public Cours(Formation formation, String nomc, Set enseignants, Set creneaus, Set groupes) {
       this.formation = formation;
       this.nomc = nomc;
       this.enseignants = enseignants;
       this.creneaus = creneaus;
       this.groupes = groupes;
    }
   
    public Integer getCodec() {
        return this.codec;
    }
    
    public void setCodec(Integer codec) {
        this.codec = codec;
    }
    public Formation getFormation() {
        return this.formation;
    }
    
    public void setFormation(Formation formation) {
        this.formation = formation;
    }
    public String getNomc() {
        return this.nomc;
    }
    
    public void setNomc(String nomc) {
        this.nomc = nomc;
    }
    public Set getEnseignants() {
        return this.enseignants;
    }
    
    public void setEnseignants(Set enseignants) {
        this.enseignants = enseignants;
    }
    public Set getCreneaus() {
        return this.creneaus;
    }
    
    public void setCreneaus(Set creneaus) {
        this.creneaus = creneaus;
    }
    public Set getGroupes() {
        return this.groupes;
    }
    
    public void setGroupes(Set groupes) {
        this.groupes = groupes;
    }




}


