package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Enseignant generated by hbm2java
 */
public class Enseignant  implements java.io.Serializable {


     private int codee;
     private String maile;
     private String nome;
     private String prenome;
     private String tele;
     private String mdpe;
     private String photo;
     private Set courses = new HashSet(0);
     private Set creneaus = new HashSet(0);
     private Set formations = new HashSet(0);

    public Enseignant() {
    }

	
    public Enseignant(int codee, String photo) {
        this.codee = codee;
        this.photo = photo;
    }
    public Enseignant(int codee, String maile, String nome, String prenome, String tele, String mdpe, String photo, Set courses, Set creneaus, Set formations) {
       this.codee = codee;
       this.maile = maile;
       this.nome = nome;
       this.prenome = prenome;
       this.tele = tele;
       this.mdpe = mdpe;
       this.photo = photo;
       this.courses = courses;
       this.creneaus = creneaus;
       this.formations = formations;
    }
   
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }
    public String getMaile() {
        return this.maile;
    }
    
    public void setMaile(String maile) {
        this.maile = maile;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getPrenome() {
        return this.prenome;
    }
    
    public void setPrenome(String prenome) {
        this.prenome = prenome;
    }
    public String getTele() {
        return this.tele;
    }
    
    public void setTele(String tele) {
        this.tele = tele;
    }
    public String getMdpe() {
        return this.mdpe;
    }
    
    public void setMdpe(String mdpe) {
        this.mdpe = mdpe;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
    public Set getCreneaus() {
        return this.creneaus;
    }
    
    public void setCreneaus(Set creneaus) {
        this.creneaus = creneaus;
    }
    public Set getFormations() {
        return this.formations;
    }
    
    public void setFormations(Set formations) {
        this.formations = formations;
    }




}


