package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1



/**
 * EtrepresentId generated by hbm2java
 */
public class EtrepresentId  implements java.io.Serializable {


     private int codecre;
     private int numetudiant;

    public EtrepresentId() {
    }

    public EtrepresentId(int codecre, int numetudiant) {
       this.codecre = codecre;
       this.numetudiant = numetudiant;
    }
   
    public int getCodecre() {
        return this.codecre;
    }
    
    public void setCodecre(int codecre) {
        this.codecre = codecre;
    }
    public int getNumetudiant() {
        return this.numetudiant;
    }
    
    public void setNumetudiant(int numetudiant) {
        this.numetudiant = numetudiant;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EtrepresentId) ) return false;
		 EtrepresentId castOther = ( EtrepresentId ) other; 
         
		 return (this.getCodecre()==castOther.getCodecre())
 && (this.getNumetudiant()==castOther.getNumetudiant());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodecre();
         result = 37 * result + this.getNumetudiant();
         return result;
   }   


}


