package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant  implements java.io.Serializable {


     private int numetudiant;
     private Formation formation;
     private String mailetu;
     private String mdpetu;
     private String nometu;
     private String prenometu;
     private String photoetu;
     private String adressesoc;
     private String mailsoc;
     private String raisonsoc;
     private String typeetu;
     private Set groupes = new HashSet(0);
     private Set etrepresents = new HashSet(0);
     private Set ficheindividuelles = new HashSet(0);

    public Etudiant() {
    }

	
    public Etudiant(int numetudiant, Formation formation) {
        this.numetudiant = numetudiant;
        this.formation = formation;
    }
    public Etudiant(int numetudiant, Formation formation, String mailetu, String mdpetu, String nometu, String prenometu, String photoetu, String adressesoc, String mailsoc, String raisonsoc, String typeetu, Set groupes, Set etrepresents, Set ficheindividuelles) {
       this.numetudiant = numetudiant;
       this.formation = formation;
       this.mailetu = mailetu;
       this.mdpetu = mdpetu;
       this.nometu = nometu;
       this.prenometu = prenometu;
       this.photoetu = photoetu;
       this.adressesoc = adressesoc;
       this.mailsoc = mailsoc;
       this.raisonsoc = raisonsoc;
       this.typeetu = typeetu;
       this.groupes = groupes;
       this.etrepresents = etrepresents;
       this.ficheindividuelles = ficheindividuelles;
    }
   
    public int getNumetudiant() {
        return this.numetudiant;
    }
    
    public void setNumetudiant(int numetudiant) {
        this.numetudiant = numetudiant;
    }
    public Formation getFormation() {
        return this.formation;
    }
    
    public void setFormation(Formation formation) {
        this.formation = formation;
    }
    public String getMailetu() {
        return this.mailetu;
    }
    
    public void setMailetu(String mailetu) {
        this.mailetu = mailetu;
    }
    public String getMdpetu() {
        return this.mdpetu;
    }
    
    public void setMdpetu(String mdpetu) {
        this.mdpetu = mdpetu;
    }
    public String getNometu() {
        return this.nometu;
    }
    
    public void setNometu(String nometu) {
        this.nometu = nometu;
    }
    public String getPrenometu() {
        return this.prenometu;
    }
    
    public void setPrenometu(String prenometu) {
        this.prenometu = prenometu;
    }
    public String getPhotoetu() {
        return this.photoetu;
    }
    
    public void setPhotoetu(String photoetu) {
        this.photoetu = photoetu;
    }
    public String getAdressesoc() {
        return this.adressesoc;
    }
    
    public void setAdressesoc(String adressesoc) {
        this.adressesoc = adressesoc;
    }
    public String getMailsoc() {
        return this.mailsoc;
    }
    
    public void setMailsoc(String mailsoc) {
        this.mailsoc = mailsoc;
    }
    public String getRaisonsoc() {
        return this.raisonsoc;
    }
    
    public void setRaisonsoc(String raisonsoc) {
        this.raisonsoc = raisonsoc;
    }
    public String getTypeetu() {
        return this.typeetu;
    }
    
    public void setTypeetu(String typeetu) {
        this.typeetu = typeetu;
    }
    public Set getGroupes() {
        return this.groupes;
    }
    
    public void setGroupes(Set groupes) {
        this.groupes = groupes;
    }
    public Set getEtrepresents() {
        return this.etrepresents;
    }
    
    public void setEtrepresents(Set etrepresents) {
        this.etrepresents = etrepresents;
    }
    public Set getFicheindividuelles() {
        return this.ficheindividuelles;
    }
    
    public void setFicheindividuelles(Set ficheindividuelles) {
        this.ficheindividuelles = ficheindividuelles;
    }




}


