package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1



/**
 * Ficheindividuelle generated by hbm2java
 */
public class Ficheindividuelle  implements java.io.Serializable {


     private Integer codefi;
     private Etudiant etudiant;
     private String urlfic;
     private String moisfiche;
     private String anneefiche;
     private Integer etatvalide;

    public Ficheindividuelle() {
    }

	
    public Ficheindividuelle(Etudiant etudiant, String urlfic, String moisfiche, String anneefiche) {
        this.etudiant = etudiant;
        this.urlfic = urlfic;
        this.moisfiche = moisfiche;
        this.anneefiche = anneefiche;
    }
    public Ficheindividuelle(Etudiant etudiant, String urlfic, String moisfiche, String anneefiche, Integer etatvalide) {
       this.etudiant = etudiant;
       this.urlfic = urlfic;
       this.moisfiche = moisfiche;
       this.anneefiche = anneefiche;
       this.etatvalide = etatvalide;
    }
   
    public Integer getCodefi() {
        return this.codefi;
    }
    
    public void setCodefi(Integer codefi) {
        this.codefi = codefi;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public String getUrlfic() {
        return this.urlfic;
    }
    
    public void setUrlfic(String urlfic) {
        this.urlfic = urlfic;
    }
    public String getMoisfiche() {
        return this.moisfiche;
    }
    
    public void setMoisfiche(String moisfiche) {
        this.moisfiche = moisfiche;
    }
    public String getAnneefiche() {
        return this.anneefiche;
    }
    
    public void setAnneefiche(String anneefiche) {
        this.anneefiche = anneefiche;
    }
    public Integer getEtatvalide() {
        return this.etatvalide;
    }
    
    public void setEtatvalide(Integer etatvalide) {
        this.etatvalide = etatvalide;
    }




}


