package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Formation generated by hbm2java
 */
public class Formation  implements java.io.Serializable {


     private Integer codef;
     private String nomf;
     private Set periodes = new HashSet(0);
     private Set etudiants = new HashSet(0);
     private Set courses = new HashSet(0);
     private Set enseignants = new HashSet(0);
     private Set gestionnairescolarites = new HashSet(0);

    public Formation() {
    }

    public Formation(String nomf, Set periodes, Set etudiants, Set courses, Set enseignants, Set gestionnairescolarites) {
       this.nomf = nomf;
       this.periodes = periodes;
       this.etudiants = etudiants;
       this.courses = courses;
       this.enseignants = enseignants;
       this.gestionnairescolarites = gestionnairescolarites;
    }
   
    public Integer getCodef() {
        return this.codef;
    }
    
    public void setCodef(Integer codef) {
        this.codef = codef;
    }
    public String getNomf() {
        return this.nomf;
    }
    
    public void setNomf(String nomf) {
        this.nomf = nomf;
    }
    public Set getPeriodes() {
        return this.periodes;
    }
    
    public void setPeriodes(Set periodes) {
        this.periodes = periodes;
    }
    public Set getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set etudiants) {
        this.etudiants = etudiants;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
    public Set getEnseignants() {
        return this.enseignants;
    }
    
    public void setEnseignants(Set enseignants) {
        this.enseignants = enseignants;
    }
    public Set getGestionnairescolarites() {
        return this.gestionnairescolarites;
    }
    
    public void setGestionnairescolarites(Set gestionnairescolarites) {
        this.gestionnairescolarites = gestionnairescolarites;
    }




}


