package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gestionnairescolarite generated by hbm2java
 */
public class Gestionnairescolarite  implements java.io.Serializable {


     private Integer codegs;
     private String mailgs;
     private String mdpgs;
     private String nomgs;
     private String prenomgs;
     private String telgs;
     private Set formations = new HashSet(0);

    public Gestionnairescolarite() {
    }

    public Gestionnairescolarite(String mailgs, String mdpgs, String nomgs, String prenomgs, String telgs, Set formations) {
       this.mailgs = mailgs;
       this.mdpgs = mdpgs;
       this.nomgs = nomgs;
       this.prenomgs = prenomgs;
       this.telgs = telgs;
       this.formations = formations;
    }
   
    public Integer getCodegs() {
        return this.codegs;
    }
    
    public void setCodegs(Integer codegs) {
        this.codegs = codegs;
    }
    public String getMailgs() {
        return this.mailgs;
    }
    
    public void setMailgs(String mailgs) {
        this.mailgs = mailgs;
    }
    public String getMdpgs() {
        return this.mdpgs;
    }
    
    public void setMdpgs(String mdpgs) {
        this.mdpgs = mdpgs;
    }
    public String getNomgs() {
        return this.nomgs;
    }
    
    public void setNomgs(String nomgs) {
        this.nomgs = nomgs;
    }
    public String getPrenomgs() {
        return this.prenomgs;
    }
    
    public void setPrenomgs(String prenomgs) {
        this.prenomgs = prenomgs;
    }
    public String getTelgs() {
        return this.telgs;
    }
    
    public void setTelgs(String telgs) {
        this.telgs = telgs;
    }
    public Set getFormations() {
        return this.formations;
    }
    
    public void setFormations(Set formations) {
        this.formations = formations;
    }




}


