package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Groupe generated by hbm2java
 */
public class Groupe  implements java.io.Serializable {


     private Integer codeg;
     private String libelleg;
     private Set etudiants = new HashSet(0);
     private Set creneaus = new HashSet(0);
     private Set courses = new HashSet(0);

    public Groupe() {
    }

    public Groupe(String libelleg, Set etudiants, Set creneaus, Set courses) {
       this.libelleg = libelleg;
       this.etudiants = etudiants;
       this.creneaus = creneaus;
       this.courses = courses;
    }
   
    public Integer getCodeg() {
        return this.codeg;
    }
    
    public void setCodeg(Integer codeg) {
        this.codeg = codeg;
    }
    public String getLibelleg() {
        return this.libelleg;
    }
    
    public void setLibelleg(String libelleg) {
        this.libelleg = libelleg;
    }
    public Set getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set etudiants) {
        this.etudiants = etudiants;
    }
    public Set getCreneaus() {
        return this.creneaus;
    }
    
    public void setCreneaus(Set creneaus) {
        this.creneaus = creneaus;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


