package bd;
// Generated 16 juil. 2020 15:28:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Periode generated by hbm2java
 */
public class Periode  implements java.io.Serializable {


     private Integer codep;
     private Formation formation;
     private Date datedebp;
     private Date datefinp;
     private String libellep;

    public Periode() {
    }

	
    public Periode(Formation formation) {
        this.formation = formation;
    }
    public Periode(Formation formation, Date datedebp, Date datefinp, String libellep) {
       this.formation = formation;
       this.datedebp = datedebp;
       this.datefinp = datefinp;
       this.libellep = libellep;
    }
   
    public Integer getCodep() {
        return this.codep;
    }
    
    public void setCodep(Integer codep) {
        this.codep = codep;
    }
    public Formation getFormation() {
        return this.formation;
    }
    
    public void setFormation(Formation formation) {
        this.formation = formation;
    }
    public Date getDatedebp() {
        return this.datedebp;
    }
    
    public void setDatedebp(Date datedebp) {
        this.datedebp = datedebp;
    }
    public Date getDatefinp() {
        return this.datefinp;
    }
    
    public void setDatefinp(Date datefinp) {
        this.datefinp = datefinp;
    }
    public String getLibellep() {
        return this.libellep;
    }
    
    public void setLibellep(String libellep) {
        this.libellep = libellep;
    }




}


